# Que faire dans certains cas particuliers ?

- Si pas ID-RNB présent initialement, décision simple (on prend le résultat du rappro dès qu'il est unique et >25m2)
- Si ID-RNB d'origine "logiciel", on ne touche pas
- Si ID-RNB d'origine "RNB"
    - si même résultat, on touche pas
    - si résultat différent et 1 seul résultat, on met à jour
    - si résultat différent et N résultat, à investiguer => mettre à jour
    - si résultat différent et 0 résultat, à investiguer => mettre à jour

In [ ]:
# chargement des résultats du rapprochement

import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

df_export = pd.read_csv('notebooks/rapprochements/DPE/2026/results_DPE_RNB.csv')

# Cas à investiguer : 1 (2025)/ N (2026)

Description de la situation : Le rapprochement 2025 a donné un résultat unique, c'est à dire qu'un ID-RNB a été associé au DPE. En faisant retourner le rapprochement en 2026, nous avons maintenant plusieurs ID-RNB associé au DPE. Que faire ? Mettre à jour ou laisser l'ancien résultat ?

- Il est possible que le résultat ait changé à cause de l'instabilité de clé d'interop, ce qui nous pousserait à ne pas toucher au résultat précédent.
- Il est possible que le résultat ait changé car le RNB est monté en qualité, ce qui nous pousserait à mettre à jour le rapprochement.
- Il est possible que ce problème soit théorique et ne concerne aucun DPE.

## Combien de cas ?

In [11]:
# Nous avions un résultat reprise RNB et maintenant nous en avons plusieurs.
df_1_N = df_export[(df_export['rnb_id_rappro'].apply(len) > 16) & (df_export['provenance_id_rnb'] == 'Reprise RNB')]

In [12]:
df_1_N.shape

(177601, 5)

## Echantillon de quelques cas

In [13]:
df_1_N.sample(20)

,numero_dpe,id_rnb,provenance_id_rnb,file,rnb_id_rappro
3004196,2265E0715973Z,Y6Q3EASC1622,Reprise RNB,existant,"['Y6Q3EASC1622', '3SMM4S33VG4V']"
5957121,2366E1459680E,DV8PPKC6WT2D,Reprise RNB,existant,"['KPW7YNXFA4KT', 'DV8PPKC6WT2D']"
9576908,2433E2036121T,N4W3V4SREZK5,Reprise RNB,existant,"['N4W3V4SREZK5', '47ZAX4Y48ZTQ']"
4286287,2226E1905999S,ZM3N81DASERD,Reprise RNB,existant,"['ZM3N81DASERD', '3JF71JVA96ZQ']"
5515219,2395E2050797O,WXRF2WZRGFGQ,Reprise RNB,existant,"['WXRF2WZRGFGQ', 'K8BB6D2GW13Y']"
9643711,2476E0683442H,8FQGMXT9WTCS,Reprise RNB,existant,"['8FQGMXT9WTCS', 'BKJVTSV83KF6']"
6904384,2369E3558528F,YG4KQYGWSB7M,Reprise RNB,existant,"['YG4KQYGWSB7M', '888YZYW4AJ1Z']"
771125,2264N0768557T,DAC8NDA34KQD,Reprise RNB,neuf,"['DAC8NDA34KQD', 'R2KQEFR54DT1']"
2628921,2184E0619723T,4XWWB6VZX8G2,Reprise RNB,existant,"['4XWWB6VZX8G2', 'QGE4C6BH4JQT']"
1386849,2529N0336772K,5SJ63N4WDGW9,Reprise RNB,neuf,"['5SJ63N4WDGW9', 'DK1CXDSAFP83']"
1462985,2235N0575793Q,JXNABM32QVMK,Reprise RNB,neuf,"['JXNABM32QVMK', 'AKZ8T2F357GA']"
2976261,2269E0237767P,EZD8BWPPRWY9,Reprise RNB,existant,"['EZD8BWPPRWY9', 'C7HKFC2JHA6E']"
6636806,2360E0157324I,HKY96VE55VCV,Reprise RNB,existant,"['HKY96VE55VCV', '68XBR6E9WHD4']"
9769190,2433E0582785F,SFPJ2C9JZCC7,Reprise RNB,existant,"['SFPJ2C9JZCC7', 'JVJMQZ22EXRW']"
6840667,2301E3329005U,Y9BTZT34V5YC,Reprise RNB,existant,"['Y9BTZT34V5YC', '1NV3XRJ4Z57E']"
12917888,2506E0064104Y,2AF2PDAPGVKT,Reprise RNB,existant,"['2AF2PDAPGVKT', 'NCZBE6BH3CS1']"
1686653,2335N0409146E,6G8DVMJX5F69,Reprise RNB,neuf,"['6G8DVMJX5F69', '13J29HPYCSAX']"
9687528,2459E1625253D,SAYGGJ3SSDRC,Reprise RNB,existant,"['SAYGGJ3SSDRC', '456JA4446FB3']"
1436032,2334N3160480R,KCDW2Z7TN2XS,Reprise RNB,neuf,"['KCDW2Z7TN2XS', 'MQJ31GPKQG8E']"
5242821,2314E1769803Z,79SEPERKC49J,Reprise RNB,existant,"['QSVDWQPNSD6Z', '79SEPERKC49J']"

## Conclusion

Globalement c'est bien d'effacer le résultat de ces rapprochements dans ces cas là, en général la situation n'est pas claire.
Ce que j'ai observé en faisant des vérifications à la main :
- souvent ce sont des modification d'adresse faites par des import de BAL qui vont mettre la bonne adresse sur un bâtiment, mais qui laissent l'adresse qui était préalablement associée à un autre bâtiment (à tort) en place. Donc le rapprochement était initialement faux. Et ne rien mettre est plus juste. exemple : 1CHF1KQHRG2M => ['1CHF1KQHRG2M', '2CGDKV1TJ4GB']
- je viens de repérer une erreur dans mon script de rapprochement, j'avais oublié de filtrer sur les bâtiments actifs mon rapprochement !
- il y a deux adresses "2 Rue du Soleil Levant, Lille" dans la BAN qui sont éloignées de plusieurs km (1 certifiée et pas l'autre). Le DPE était associée à l'adresse BAN non certifiée.

# Cas à investiguer : 1 (2025)/ 0 (2026)

Descritption de la situation : Le rapprochement 2025 a donné un résultat unique, c'est à dire qu'un ID-RNB a été associé au DPE. En faisant retourner le rapprochement en 2026, nous n'avons maintenant plus de résultat. Que faire ? Mettre à jour ou laisser l'ancien résultat ?

- Il est possible que le résultat ait changé à cause de l'instabilité de clé d'interop, ce qui nous pousserait à ne pas toucher au résultat précédent.
- Il est possible que le résultat ait changé car le RNB est monté en qualité, ce qui nous pousserait à mettre à jour le rapprochement.
- Il est possible que ce problème soit théorique et ne concerne aucun DPE.

## Combien de cas ?

In [14]:
# Nous avions un résultat reprise RNB et maintenant nous n'en avons plus.
df_1_0 = df_export[(df_export['rnb_id_rappro'].apply(len) < 16) & (df_export['provenance_id_rnb'] == 'Reprise RNB')]

In [15]:
df_1_0.shape

(27897, 5)

## Echantillon de quelques cas

In [ ]:
df_1_0.sample(20)

,numero_dpe,id_rnb,provenance_id_rnb,file,rnb_id_rappro
10487406,2491E3965865X,K54AHYC1WE7F,Reprise RNB,existant,[]
12640247,2513E2014694X,WDPXEN8PKKR6,Reprise RNB,existant,[]
5071207,2285E3195418A,XXK3YWQYDQM3,Reprise RNB,existant,[]
1100432,2213N0402933I,FH3B6AQPST6R,Reprise RNB,neuf,[]
11619877,2477E2944951L,ENGGMPJXD54R,Reprise RNB,existant,[]
3539578,2214E1317172B,85685WQ2Y1YH,Reprise RNB,existant,[]
1603749,2344N4277916J,CVYJP73JC4Q3,Reprise RNB,neuf,[]
5731669,2369E2214709W,FMAGXXMDWSC3,Reprise RNB,existant,[]
12235879,2569E0084949C,F2NZNNK8EJZF,Reprise RNB,existant,[]
14804811,2476E1402637Q,Y6445ZQP7PD9,Reprise RNB,existant,[]
2794524,2176E0676417Z,1SYVEVMKCPAR,Reprise RNB,existant,[]
6100903,2379E1512669S,JS1MJKRP1R1P,Reprise RNB,existant,[]
4431634,2250E2534684V,BWEYHFTA5KMY,Reprise RNB,existant,[]
7865247,2317E4309222B,253AS7JY5W4K,Reprise RNB,existant,[]
7909298,2369E2399403M,9CRTARWZ1GYJ,Reprise RNB,existant,[]
12684990,2569E1659357G,BT1AZJKNWC79,Reprise RNB,existant,[]
5304428,2314E2214923Z,M6EZ916QZY3V,Reprise RNB,existant,[]
7298937,2333E3611184B,N9YZ78S9VN8E,Reprise RNB,existant,[]
1331276,2335N2933033T,4SEXZC7CPMZX,Reprise RNB,neuf,[]
8291820,2359E2745601K,RGX8DNMA5NMG,Reprise RNB,existant,[]

:

- 11314000	2401E2754581P	7MXTM4P3V55T	Reprise RNB	existant	[]
- => Probleme car code postal ban = "01560" et code postal brut = 1560 et on exclue les résultats lorsque les deux chaines de caractères sont différentes.

Tous les cas semblent similaires, les codes postaux bruts ont été mal exportés.
Je vais adapter le script.

- DPE 2491E3965865X (K54AHYC1WE7F) : le bâtiment a été scindé en deux, mais les enfants n'ont plus d'adresse associée
- DPE 2513E2014694X (WDPXEN8PKKR6) : changement de la clé d'interopérabilité